version: 2.1
orbs:
  node: circleci/node@5.1.0
  mongodb: circleci/mongodb@1.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.16
      - image: mongo:5.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Run linter
          command: npm run lint
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
